# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudini < Formula
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.1.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jercle/cloudini/releases/download/v0.1.16/cloudini_Darwin_x86_64.tar.gz"
      sha256 "b8d0fc96c6686e6fde480c09752fb56ec46eb661726ef4cb2f555dcf307c0aad"

      def install
        bin.install "cld"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jercle/cloudini/releases/download/v0.1.16/cloudini_Darwin_arm64.tar.gz"
      sha256 "b5233e2184ea56042f7c5a6b1184062e600bd37f2e093aa7a68ce9418a5f20e4"

      def install
        bin.install "cld"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jercle/cloudini/releases/download/v0.1.16/cloudini_Linux_x86_64.tar.gz"
        sha256 "0e02def9a10ccf64df479d0bc5fef3244e2dd1d51f9ee379398a234e8498d73c"

        def install
          bin.install "cld"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jercle/cloudini/releases/download/v0.1.16/cloudini_Linux_arm64.tar.gz"
        sha256 "1f6d0d865a7442d73b690ffd51aff3030810d347acca109bb649830e59b038a4"

        def install
          bin.install "cld"
        end
      end
    end
  end

  test do
    system "#{bin}/cld", "--version"
  end
end
