# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.44" do
  name "cloudini@0.3.44"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.44"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "97a3fc54d4135534b3fee45d208acd0ff52acaaf23a01c7f91b2bd4ef8ba267f"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "f107589ba05219efc49a59c8a3715f8113bdc246990774a07dc638ebf63e0a8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "8fdabeb0039339077ebc85675e969a995f7e8dc59aa4d0b5fb91054affa44232"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "bed95762af7954dd70c8773867fec46b65aadfb75bb46a6454ab2043dab23c6f"
    end
  end

  # No zap stanza required
end
