# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.69" do
  version "0.3.69"

  on_macos do
    on_intel do
      sha256 "517bb0082dc258dd63f661b32c386dadfc7d018663fa04189a3dda530c8b3e3d"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b8412777051c47cd1a0a32f1cdc68d7813a4a086a7210acaf00dbca106fa783a"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef542e3266eaabaf1a71e1b898c4025b8708d3a6e7f8aa561950a0440897dd39"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "21d170c867b221ef0bbd9265ddd3ab2d6e9167727ec81321ab634330b8136f98"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.69"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
