# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.36" do
  name "cloudini@0.3.36"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.36"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "38205810e0dd08333975233bc605ed0b12a78903bb8cfef3fadd97ec40e01574"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "d073e10d8306649779075aa0251479b02509e699300186a838ef68f033d85b92"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "abfd282479c72e76a49690f56d7b393a9f07f6e27b1566ae178afabd34c19714"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "a7c142d07d994f1f782c2514a7b5bf3f827da85d80b063c54b35375903248ed9"
    end
  end

  # No zap stanza required
end
