# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.18" do
  version "0.4.18"

  on_macos do
    on_arm do
      sha256 "16166f470a67b4573438cb4b85b2d7eba2a76b562bacd300dd2772dd67a4d541"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ec00a5560d83bb6df49d5bc07850ba2342b91846a2e5d34d805182f05ddc69b"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e021d90420c7cd220dc4b9e6f7f41238619fe7e86e380369c4130903ea2cbf0b"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "84949bb1ebe35724521a5c6a3de09566348b4a00eb9ac3795aa337f86979efa0"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_x86_64.tar.gz"
    end
  end

  name "cloudini@0.4.18"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required
end
