# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.8" do
  version "0.4.8"

  on_macos do
    on_intel do
      sha256 "a3f4222481a78206747e02eeedda4c0ca853f50ff2664d899641b10ad0f1b49c"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "52ef37145e2d88957c5d46c27ce5921ee62f17f105bd8806b356cef4bfcb848f"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "49055d3e4ae152e2989471f73bc1354226b9e10ac8d6f9c7ad9855f84bcc1d18"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "835ab483f382c30864455237b80c49453fc860bc84ec898bda0c523444cd75a8"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.4.8"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
