# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.45" do
  name "cloudini@0.3.45"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.45"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "63138c6a512e3e825ac42fe71db50ca899f3611f82ae8b57f00a01b419366fe6"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "e0043ffda71636b26a4e6f95806dd356ef5d056ea77e4a5b730c399799a1a1ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "b4e4f0aa46bbbeac567585b36497085a00cfa3dbc04f10ca2978a33a48a1c2eb"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "78d7ee09b068649eecaedf1bfa74729ff8b014b7f99ab52dee770ea1bb1c0511"
    end
  end

  # No zap stanza required
end
