# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.42" do
  name "cloudini@0.3.42"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.42"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "89f3dc97f474092fcdbdcf669bcbec064ea991ff921e3f0bab23b5ac5ab79be4"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "05a01b2f2a70e7313a9c6831ecdfcc26f69658c2782987043b833337fb07ae2e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "49de4de05e312e1b7bb5513e83ff7f37af2ce739e28b8f58cb4761dd09d79920"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "9cb3a6756e45a034887f1f657d949936f5ef238aae97c51a04a20b7c449db141"
    end
  end

  # No zap stanza required
end
