# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.52" do
  version "0.3.52"

  on_macos do
    on_intel do
      sha256 "0738af34629ad5e9b3cdd13404c2d528b8c958c716ab10769ca11ad8b0d5faea"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4c57accd6dbb40b376ac7319abb4d47a73bb1565aed9681b9e7b1a5ed1f38188"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "afc7c11518b2ae6f75cad359e97da7c212dbaa422a26ef0ab19cb3d40636d8cc"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4b8a9684fed7a916b415cb37e99668aa1d1eeb36acdc67a74085a2704db4a1c4"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.52"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
