# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.2.0" do
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.2.0/cloudini_Darwin_x86_64.tar.gz"
      sha256 "2b489a4edaad2eeec9aecd380604a1697ad7c63dff163be0195e63e7c96abf8d"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.2.0/cloudini_Darwin_arm64.tar.gz"
      sha256 "c6caa62152dd99cfd67f6a97a4172662bdfb5e974b799a46a7643c2ecc837066"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.2.0/cloudini_Linux_x86_64.tar.gz"
      sha256 "8cc253757afe10a2dac00695e1e8833d1db81e18b205f4fa476fd62a6ef06cdb"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.2.0/cloudini_Linux_arm64.tar.gz"
      sha256 "22596a1cdd059ff2fd107ec147e0e70196043e57bfb708db1bb2b4c87c1be939"
    end
  end

  # No zap stanza required
end
