# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.38" do
  name "cloudini@0.3.38"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.38"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "6db13e630166d1634eafe330dfcd5135484adb51a573ae4f919e09fd09b45927"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "42acab9b8f5ccc1dafe4a15aed51c527e072b6a1029833331a8d31d6d6a09d0c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "cfdb79c0f30e8c8adf01df88af68b4766a4df89100418ff41221ca56f04e3092"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "06ea73f6aa088b4dd458bbc542bf7f54acbc9dc186add2d2032a5e92fe3066ac"
    end
  end

  # No zap stanza required
end
