# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.2.0" do
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.2.0/cloudini_Darwin_x86_64.tar.gz"
      sha256 "e801bce07e696509d3d3dd64749e0ef45f1af1e12b46b1d5421af85fb8f29726"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.2.0/cloudini_Darwin_arm64.tar.gz"
      sha256 "2c73f4a0fa88ca671bcd39afa1b380ab5df521fe4e8354b87b180018b487458a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.2.0/cloudini_Linux_x86_64.tar.gz"
      sha256 "5ef897f18d9e8047b0b817da1e39d1051afab9c692b557938589085fca0f8c84"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.2.0/cloudini_Linux_arm64.tar.gz"
      sha256 "fd2dd9950b82e1e816db32d2261fa9783539c404113ed317f24feda43b4c0479"
    end
  end

  # No zap stanza required
end
