# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.35" do
  name "cloudini@0.3.35"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.35"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "cbc5a7b7e237c3097dc1a433c7c76b56aca9aaacc1f7137bfdfa16f55d922613"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "ff883e1df1fbc465408e46fc3da12d5dafa170efc66ff3f0b8016d4597db882d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "6fa0d25740d059e80d8689365a5262a82b45123797b24b789ef22f5af279de1c"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "7cdd00349d4591bdc1e3c5d00833fe835a28dfb671222cd5d5b330e189b77376"
    end
  end

  # No zap stanza required
end
