# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.1" do
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.1/cloudini_Darwin_x86_64.tar.gz"
      sha256 "d4d589750f7b7e10edb66591d13557703ab40882aa7acbf70ce9bb18cd541545"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.1/cloudini_Darwin_arm64.tar.gz"
      sha256 "ef230aa44e37556640be68d3f2a0ffa18a39f4af57906b90267b2fa21a8ace55"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.1/cloudini_Linux_x86_64.tar.gz"
      sha256 "b22a36d4e59bda23829cded5c1811bd050992145c48973f73cd5f792f39cc0b5"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.1/cloudini_Linux_arm64.tar.gz"
      sha256 "5edd10c983df3ee982f405a50d14d7709c18094b91487219e6ea712941704de8"
    end
  end

  # No zap stanza required
end
