# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.31" do
  name "cloudini@0.3.31"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.31"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "48cb00aee1b7e8e837b48e6d3af02270d4226b076e585eb96789619ea555bbee"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "6aa2c361746a0e3a1ec5088f768701d5d3572d245a3710c9d6ed724e0b88980a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "0f7d519deb9f93c5d160792a3ac6210346ab42e51a8fd2ca5aa2e18eca963cce"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "f47afd2f0ed54512a9269bc94612cbac562c94ad350955df8cea4950433c5659"
    end
  end

  # No zap stanza required
end
