# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.9" do
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.9/cloudini_Darwin_x86_64.tar.gz"
      sha256 "9cd9b3aa4ee05e00ba73c0659bfc9e1a4d30e49d7523c35cfdc1f62182094da6"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.9/cloudini_Darwin_arm64.tar.gz"
      sha256 "fefe104e421a81a3932e20dba5be409d410a51b4a4190bd27aa6282dc0f33dee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.9/cloudini_Linux_x86_64.tar.gz"
      sha256 "30e849a1048b2f2aaeed5ee694b2cc4638cf19ebf52c20ddaf3481864ed9d4d8"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.9/cloudini_Linux_arm64.tar.gz"
      sha256 "37876da68c4a9c6a791f33ac97bda742ff7581fd68c7ac78632c4ee20e2522c3"
    end
  end

  # No zap stanza required
end
