# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.58" do
  version "0.3.58"

  on_macos do
    on_intel do
      sha256 "115352d4ed259e576507acdaef7e0611794bd3dff1be2fa207f1cd8315aedbf2"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d6443c0c93b76f59cc987a0306e754d32cc7f9391f117c67a5b29f145dac5d2c"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3cc9111b8491884b7ede9a2a3fc4e2381419c37cbe5c8edae951e99d0bf29af9"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "351882870e0be0c14e9df6e27bb8de55cf335cd4534ba561405d044c795b5496"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.58"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
