# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.0" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "cd85937b37223c604977517febbdd3230a13aed93c2fcef312e112cf4f46cc57"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "283df42039d93d985506e8c6cc178449e0f3540cfd635be82c0ff11830373a86"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3eda70a4789ac088ad8e6b8709148e016e5779bfc2d1eded5facc97973dadf6a"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8c35cbfba946736c1b66a6c0ae480af23d4184923464f2cf85b6b81629d8e1bb"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.4.0"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
