# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.27" do
  name "cloudini@0.3.27"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.27"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "08cec62b5bfbf3fece3bc018917d80c19cda51e5848960602793e3c00bd77ead"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "eac90e7b2cc404213d0173850459d1377595d0b56177796114b6517461a0dc60"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "2b8f437ade65aa9e6f13ec996b7ce4a08e0fd3cd5d0cb445a3e6ddb46c84462c"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "2363debe590292bf15201ba43775603a6f0f11118f358e063177802be6b8b89d"
    end
  end

  # No zap stanza required
end
