# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.12" do
  version "0.4.12"

  on_macos do
    on_arm do
      sha256 "97afe9b419d332d9043f7dfb4f21ffa6f5cdf9ea121476b39976ce9b33a11dc3"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "31e95d450642993138379bcf5e9f1321fc82db79ec37a8e681ef480f0eef59de"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a7ba4ae16da89b742ed217e1f4b555f85cade0320358b523e5f4ff883c23f463"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1fb8a6646d3f1a1b7570d711a586348d8df55acb0086d51adfabc514a124e2d"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_x86_64.tar.gz"
    end
  end

  name "cloudini@0.4.12"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required
end
