# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.50" do
  version "0.3.50"

  on_macos do
    on_intel do
      sha256 "9ef16698fd004a2803a2b9000256c44203b7996b405bbc0a4edc8b13f3d1ea4e"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d318430115932f5a61cf969dfd07a042912b3080a59bf799b189383950caee17"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "19f2c5dcc519cb9f275ab93ed81af88b97e42ea3f64cf41304ab9ac69a168ccb"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "aafe215f96db09d9e3ff3109370aa9febc86edd25c905bc635d535cd3f8ea717"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.50"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
