# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.60" do
  version "0.3.60"

  on_macos do
    on_intel do
      sha256 "ee92108b721960e6a35f9758ee286171673346802d8090659c24b25a8a1a99da"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8b8649e572cbb88ad2e3f55cdcb689ce96ab43be9945f06edfee1e1996e93256"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a6f7d523afcc48335749c1744a780b458c0036f200ead9fa2be0b42dd01ed126"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "90ed1c616a72e1a22fa6b758fd019ca90b9760bcfb51d009ca0dbb2102c9dade"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.60"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
