# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini" do
  version "0.3.51"

  on_macos do
    on_intel do
      sha256 "24c3f224d2cce83ee5bb223240893bf4acdace44c659f3c5cb63a4af9f5725f1"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c850e8749dfdaac7fe6f3709b79a609b4c4f8d3feb213b669af7080c8fc3c5f2"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "910f8f801fa37efffb498a2412f71d4922e714dbdd29a8354242d81c20fe9297"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "562bccaa569a3fedea0e64be26d96d982db8d1d4d1a4ecbcbe93f90a4fa820a9"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
