# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.54" do
  version "0.3.54"

  on_macos do
    on_intel do
      sha256 "5d0b658bbb5fcd04363fbcd7ae419c7bfd92aee4c8d56917bee3e80ebae27180"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8997177a2f450cdc3af431302be2c1eb1138f128f94329e18acdbc088f746d2f"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "81779221d9fd7840d2a25aed745a747427242abc241d37ad95e54a068a4403a4"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a2fdd10e0b1fba2ed66e32e0c62a174476ca9de1959bde515ee32ee8f510ca69"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.54"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
