# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.13" do
  version "0.4.13"

  on_macos do
    on_arm do
      sha256 "dd5250979d466c892c6e543d42e1b0e70eec9b52ee6975841c0de607d15ab9a4"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e3b804cd381861c255289d56262d0b6fccc8d9a8c241c2f05b240a66d283a3a"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0306f57ee5f0c86515eebaa98c9bc99d72e0cb8af6084a5b781e43754853d2de"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "372aa013f9522feaaa213e12b682671b7d3b9b487a589744dc536c644a629f02"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_x86_64.tar.gz"
    end
  end

  name "cloudini@0.4.13"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required
end
