# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.34" do
  name "cloudini@0.3.34"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.34"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "72d29aead6bc37c95abc9e96c48d72b5ecb0aed235da4876da1b89c14bf7db5d"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "7c3646cc1e25ee6049123947800f3aaa8292da1cc1595615ec24ca7d39a2b47f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "8a5ec8ed23f297b8bfb619a57d5f46624dfc6d45dc669b92af20aaac03a22c36"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "86bb4ae26c69c5ba1efcd33a4294d8ca4addb6626eae469abbb741b438677147"
    end
  end

  # No zap stanza required
end
