# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.59" do
  version "0.3.59"

  on_macos do
    on_intel do
      sha256 "bb48f8759a9ae4c35d157f7c407794a024224bb6afb38719a5e23e77c952a5b3"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0dbed89fe1fffb35283fb04e0199d1f5a3c13c5d1bf56ec539e56b6a35c74848"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9fae3e8f7a2698933408c30e6b2fe41dcb0ad4751618d52d9084909915fc565e"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e83ded382df96657931d98a4f4bf68b8e4aff44560075cbd1cc809ccef1b3d47"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.59"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
