# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.48" do
  version "0.3.48"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "971e677180d138ea29e5769542503abb3b3025df7d56f4b998e72b9236e1671f"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "f479bc74592c1c1173c5a51a28993e10a69316890c47d4dc6905012ebf16fdf5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "2bf27775c27042bc5e7781588fe61a10146f15728bd97b9ce9b7b25328cd90df"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "95f0be454f9c473852f396bae116a1f6f4347ecccd42ab45017b7afb949d8083"
    end
  end

  name "cloudini@0.3.48"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
