# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.0" do
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.0/cloudini_Darwin_x86_64.tar.gz"
      sha256 "d8ca22d154134638c0ef37a9ac5c124977ce0b82f2d3352e83ca5631d5b50760"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.0/cloudini_Darwin_arm64.tar.gz"
      sha256 "2f08691b943dc69cea56020463f5de9e11a7b7f33b8f1381e63ca2aa3d27a10a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.0/cloudini_Linux_x86_64.tar.gz"
      sha256 "bdc8422e4ea40d4b653f6849d765050a1e7024b5cba47d8053cbe5f3d93e121e"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.0/cloudini_Linux_arm64.tar.gz"
      sha256 "9ded92e8e4a643f740e1f932cb0edbbe2ecc4756f93bd63c148b276376000ca2"
    end
  end

  # No zap stanza required
end
