# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.22" do
  name "cloudini@0.3.22"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "18381f690a8a4bfb23b3bc1657ea69d4d401873a66863e6cf74641d983df6429"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "10e7523854e989f0b4a20abc8f4d690e7bb93149433f5fa7119ef65b5bcd268d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "248a826b7341f03bbbd5598723ae8e3e2f1e5c00013810765aa6adf883047b36"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "d627121c70b1cf2d886d0ba65a4c33a3bdf2b40895bf6dc6df1b6f313e747c40"
    end
  end

  # No zap stanza required
end
