# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.14" do
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.14/cloudini_Darwin_x86_64.tar.gz"
      sha256 "8d54f05f5207cab152bc2043c1778ab7b7d9f4b82a0ec0f3e57b2389d2bf0ed4"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.14/cloudini_Darwin_arm64.tar.gz"
      sha256 "27b3f5d8ed5bc6d679d450477e49882ad3ae8bc9f84e7510b54e49e8a65d1579"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.14/cloudini_Linux_x86_64.tar.gz"
      sha256 "fd8f4d1926777928aa0f56475038560ade38fc287483ebe2c8605bd83705f866"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.14/cloudini_Linux_arm64.tar.gz"
      sha256 "926e31fa29b12f4779b91191b9f026164e24e8bf8731b820befe717df2323691"
    end
  end

  # No zap stanza required
end
