# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.56" do
  version "0.3.56"

  on_macos do
    on_intel do
      sha256 "d1d85417013a67d0aa84e0921a4b3b0b60d2b856148c16889c60bed08df7aa6f"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c541c026bb28ffb37a3c42203c7458f23c4d62d8b9947aaaeccf6e99d6dee594"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9f5e129fa7da7deec06651fe3ae5cae77c39b3196f1356f65a293cc7fbb002b1"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a1a3fa60733c7870f8228d7f131951bc4ad7db89ce0e26bb0bd430080e879c12"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.56"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
