# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.37" do
  name "cloudini@0.3.37"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.37"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "d4184e988ecfdd1b71029bed706b00782f21cdcee8846b2f47301718c5c3cb3f"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "e66d83f409481c5deb4d1ae219ffd511a19c070593560d3f246b55b8b3c79675"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "656d72e7ffe7336722f4f1637914539a3aee5567d5a6d6bc15beed8e909e36a4"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "614ae602dc92b5994f64927866e88a5d944f9623a7310d620c6d11d51088f3f7"
    end
  end

  # No zap stanza required
end
