# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.6" do
  version "0.4.6"

  on_macos do
    on_intel do
      sha256 "2e2d7641bf964e3bcd199f1e7973fba359dae3d101b6fe6d2ca5554a24dc7ded"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1b05a1f5e9b56cada030ec7a6961abfa542e44d71df49ec1ce4052bcbc2de073"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "424b82bfe3596c8f782296b8df261955569c8d18dd6cff62eadcab8f7af703b5"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a5882437d9fcccc50fcb3781861921c855cd128de85fd30bfed4fc6c35092249"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.4.6"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
