# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.66" do
  version "0.3.66"

  on_macos do
    on_intel do
      sha256 "d8f26862c4501b3d188ef2dcd6921306ef9b920dcc60e422640f9f03378763c3"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b074cfee394dc534c84d4e8f21167eeac8393cf00fe30dd86e4b17a66bcbe7c1"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "524258f0a6b5cde036b1c462df9fdb96cfa3e71c31cdece7add633eaf91e2c3d"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6743d089b2e705dcb56a3cb9b911d20e763a1a9a61ac4cf16ee6eaf4a5834614"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.66"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
