# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "6264a0ea61483053235c9fc9bb0f24a479eec47a6404970cacf0825ace5089f6"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e6f49f28b0cbf24f01d72a99d767f8aa54b9b051c3f78a85a229c68440fbb861"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b890724bbe7a27f449f1e94de20abd6daff51be5c7891274d0c62889d4c1c52"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9c8dc46bdbe6dcd7dfe836ab0eb481b08c554711e9de618dd2c7604404c8bc98"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
