# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.17" do
  version "0.4.17"

  on_macos do
    on_arm do
      sha256 "96e09f8b30e844fa92ea874ba107a3035c68ac6eae01202832cf7920212ff1e3"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "967d7c526ec6eef2dbbe95a36c32fe103e1c7acb6ced107d5851693a61a32fa4"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b6ade1715f84b93b79af44b48763b1425b2f7d04f636ae399bc183e1134dadae"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8fc26b17e9a3facb5170968c3353c2ec18b41dfcbaa5d6f1c0b509669d83e11"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_x86_64.tar.gz"
    end
  end

  name "cloudini@0.4.17"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required
end
