# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.68" do
  version "0.3.68"

  on_macos do
    on_intel do
      sha256 "e6774c51a0f38d4fe2417c6142c0357ec241e5aae8ad2c251778a3c73edf592d"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "555ea601d58d992433e50003066d8edcb4ed757c143a42dc570d7549457dcace"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b09304aa27d3baf4b4e021030a4b660387c076f86c85096075023ae6de5908c7"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "31afe3071d56f8ed957e3e44272ac6403653aa8c86b6220e8b9994ea09c54db1"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.68"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
