# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.1" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "a8ebaf52cfc2cfbe80df00bc0feca3d1d673afff93dab4fd6c4ba3afa8c98961"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "15eb1fe57239415d2d49e38842df1f92233f624991e20de4cc2c0e17c94db8a6"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46b3fcd636c9333dd1848955405c6f3d2e224e4a3c42a560b031616e45e1f4c8"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0512329b2c82196f58684a75445f0857882e9fe6e19370046a885687528a8e01"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.4.1"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
