# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.53" do
  version "0.3.53"

  on_macos do
    on_intel do
      sha256 "d7ba62db134a17ec298389d61e68d54f2a273e338fc757251b344f464ef673ed"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "99db6fedbdca67269b9db8720e088f3ade275ae7790f9cde80da5ee800197e1b"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "37105765871c9c084b9e618225eb06180ab3fd4de7d8b988589e3ec8edf88048"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6afb9f2f3ac19a0457d3b3ff0a3323ac701fcbca6789cc161c6ce292a579df0f"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.53"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
