# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.10" do
  version "0.4.10"

  on_macos do
    on_intel do
      sha256 "7310737573290b8c02722b2b2217bd4806ceff12c4f3e668198af5b6a74b7bed"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "38fb55f4911d6496146083affe46e5d872ffdde83360560ec17623d575219f76"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6771afb21224ebeec728de002356340e045fa470b4a1df7c670212fd370663f4"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2e6856ff05c509a7082bb0c246ea590a7e816481e81cf0d4fb6c432809ec1b87"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.4.10"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
