# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.14" do
  version "0.4.14"

  on_macos do
    on_arm do
      sha256 "a0ec3a2ab6b0be57c48d12626ec592e724f3eb8f5bfe8b8b4148633053fd5ab9"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "099de48f49afaf058a3c400b8b1867c5cc344a4b0d3344a58642c600e13b15f9"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "275634fa5fbb5ed9a3fc8191426ac73b2fde90c81b97125ab24ea186175f2a40"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b968cded796d53546f72c0f4f9fc07775a0b4b5b05481e25334787c226db771"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_x86_64.tar.gz"
    end
  end

  name "cloudini@0.4.14"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required
end
