# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.46" do
  name "cloudini@0.3.46"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.46"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
      sha256 "3f42995158905ac476d4f7c3c16d633ce997f5b5c1ca4685eedaf9d22e86e7ba"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
      sha256 "c0ecc69fc9914d854c20983c3b48c24a98de13bbfd040cfb1d970418e27f58b6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
      sha256 "491e661f331a1cb4a70f9eeb2bd7cc4283135b606855752f6ecc2565c5fe11b5"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
      sha256 "74fa0e48b6f6326b9a36dd0c94a22d84e8a5f0f97fcb0ab4df2a597596282307"
    end
  end

  # No zap stanza required
end
