# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.4.13" do
  version "0.4.13"

  on_macos do
    on_arm do
      sha256 "5c79b06e6b41c7bcfb69ce6b01b94cdc163cdb90631cd4b21b0ae5e533cf64a5"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b0042968636050045ed6d48a100c341efa187653696486aefbc57b1db823d703"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8365829afe901104afcd2f65d62a05d9c32452ce2b269c19af6f31d9a42230d9"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "99ea3412268fdc4c55f5df5fa0ddb5b24821f68b99859cc9966095e254d2e428"
      url "https://github.com/jercle/cloudini/releases/download/v#{version}/cloudini_Linux_x86_64.tar.gz"
    end
  end

  name "cloudini@0.4.13"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required
end
