# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.12" do
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.12/cloudini_Darwin_x86_64.tar.gz"
      sha256 "e1bc0efaa3ac823ae49641d0bf36ca2c4b0b5d20f64b4d2bc64c7e40215aaf55"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.12/cloudini_Darwin_arm64.tar.gz"
      sha256 "3c6332074526e253a8c2293b0bbde6423f43ec918c5ea63830ef305838b87e19"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.12/cloudini_Linux_x86_64.tar.gz"
      sha256 "59dd30b8f045704873e68faf15b974b86be968d67cf9744302f8afb622676b8a"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/v0.3.12/cloudini_Linux_arm64.tar.gz"
      sha256 "036939053fff8057eb1bfff7ca8134f96cb8e2627b43c654bc36571dd67b06ac"
    end
  end

  # No zap stanza required
end
