# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.61" do
  version "0.3.61"

  on_macos do
    on_intel do
      sha256 "6426bfcec7c278dfb4d985d13be48f256c901adea4105e074b973619581b000b"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "318ddf9b12924bca6e9d7992361807343a1a629176c62ff591e6ec68b68478cc"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7238e7e02caaf1ff4a917606e9a3528da9464e61d8b7c1b47be90b0e93401958"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2c966ebdc3146565c57db4eb4069e4ae1818e560bc9bd3cd6d20c45c8c980c5c"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.61"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
