# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.64" do
  version "0.3.64"

  on_macos do
    on_intel do
      sha256 "91b321cdf39c92609914effb2033163fa7b70ab94a354793bbf46af864acafac"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bc1c42a8de2512c2ca632dddbb7d730c666f135886905e5f1d1b99c79806db6b"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a03af65fac4585f54860c7bd73bdd311ecd5c2504ea485fa25fea0d4d7cbc76"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "77cbeaac0ba4a8288ddf2069baa1bc0fd40b9cd7421d1b8a9cf256e91dca14c4"
      url "https://github.com/jercle/cloudini/releases/download/#{version}/cloudini_Linux_arm64.tar.gz"
    end
  end

  name "cloudini@0.3.64"
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  # No zap stanza required

end
