# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudini@0.3.15" do
  desc "Cloud CLI providing functionality Azure CLI doesn't. Soon to add GCP and AWS features."
  homepage "https://github.com/jercle/cloudini"
  version "0.3.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cld"

  on_macos do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/0.3.15/cloudini_Darwin_x86_64.tar.gz"
      sha256 "d15433b1c62f26e3c800938cf937bc7cffc1bc2a8d43f132341090a25a68e63d"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/0.3.15/cloudini_Darwin_arm64.tar.gz"
      sha256 "d2b6ba50cd4dace2736e3e31e15143b8b4174d9c0d53535c3d2bd800b4dd46c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jercle/cloudini/releases/download/0.3.15/cloudini_Linux_x86_64.tar.gz"
      sha256 "589396fd7df40a6edf66710cdd31c0e9dd5fa46ede9df68d222706288c510bd8"
    end
    on_arm do
      url "https://github.com/jercle/cloudini/releases/download/0.3.15/cloudini_Linux_arm64.tar.gz"
      sha256 "d1c60b384379ed04c402e7678040ddba3898b52ac6e62c40488a2ad2d22a60ea"
    end
  end

  # No zap stanza required
end
